name: Cuentacuentos
options:
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

targets:
  Cuentacuentos:
    type: application
    platform: iOS
    deploymentTarget: "26.1"
    configFiles:
      Debug: Configs/Debug.xcconfig
      Release: Configs/Release.xcconfig
    sources:
      - path: Cuentacuentos
    info:
      path: Info.plist
      properties:
        OPENAI_API_KEY: $(OPENAI_API_KEY)
        UILaunchStoryboardName: LaunchScreen
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        DEVELOPMENT_TEAM: PQH3T5E4L8
        PRODUCT_BUNDLE_IDENTIFIER: com.mtailanian.cuentacuentos
        PRODUCT_NAME: $(TARGET_NAME)
        SWIFT_VERSION: "5.0"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1"
